% update magnetic fields

current_time  = current_time + dt/2;
    
% TEz
if is_TEz
Hz(pis:pie-1,pjs:pje-1) = ...
    Chzh(pis:pie-1,pjs:pje-1).* Hz(pis:pie-1,pjs:pje-1) ...
    + Chzex(pis:pie-1,pjs:pje-1) ...
    .* (Ex(pis:pie-1,pjs+1:pje)-Ex(pis:pie-1,pjs:pje-1))  ...
    + Chzey(pis:pie-1,pjs:pje-1) ...
    .*(Ey(pis+1:pie,pjs:pje-1)-Ey(pis:pie-1,pjs:pje-1)); 
end

% TMz
if is_TMz
    Hx(:,pjs:pje-1) = Chxh(:,pjs:pje-1) .* Hx(:,pjs:pje-1) ...
        + Chxez(:,pjs:pje-1) .* (Ez(:,pjs+1:pje)-Ez(:,pjs:pje-1)); 

    Hy(pis:pie-1,:) = Chyh(pis:pie-1,:) .* Hy(pis:pie-1,:) ...
        + Chyez(pis:pie-1,:) .* (Ez(pis+1:pie,:)-Ez(pis:pie-1,:)); 
end               
